---
services:
    nginx:
      image: nginx:latest
      networks: 
       - homepage
      container_name: nginx-container
      ports:
       - 8080:80
      volumes:
       - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
       - ./data:/usr/share/nginx/html:ro
      restart: unless-stopped